### PR TITLE
Fixed a thing

### PR DESCRIPTION
**Pull request by TentaRJ**
why wont people support us mac users 😢

### CODE REVIEW

**Comment by SuperPositiveP** [comment]
To answer your question: Mac is a bitch to compile for. Trust me: I've TRIED to support you guys lmao. Binaries either crash outright or crash after completing a song, and I don't think it's my code lol. Anyone else who tries to build it gets the same.

**Comment by TentaRJ** [comment]
> To answer your question: Mac is a bitch to compile for. Trust me: I've TRIED to support you guys lmao. Binaries either crash outright or crash after completing a song, and I don't think it's my code lol. Anyone else who tries to build it gets the same.

are you trying to compile for mac on a windows machine?

**Comment by SuperPositiveP** [comment]
Lmao no. I used a vm. I also had a guy with a real Mac and a (I assume working) mac version of his own mod try it and same issue. This isn't the place to discuss it tho, I was just giving you a straight answer.

**Comment by TentaRJ** [comment]
Forgot about this :/

**Pull request closed without merging**
